on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Log Payload information
      run: |
        echo "Path: ${{ github.event.client_payload.path }}"
    - name: Invoke webhook on Repository chatbottery-gpt-service
      if: ${{ !endsWith(github.event.client_payload.path, '.json') }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/das-buro-am-draht/chatbottery-gpt-service/dispatches \
          -d '{"event_type":"on-published","client_payload":{"status":200,"path":"${{ github.event.client_payload.path }}"}}'
