on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Log Payload information
      run: |
        echo "Path: '${{ github.event.client_payload.path }}'"
    - name: list workflows
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TEST }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/das-buro-am-draht/chatbottery-gpt-service/actions/workflows
    - name: Invoke webhook on Repository chatbottery-gpt-service
      if: ${{ !endsWith(github.event.client_payload.path, '.json') }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/das-buro-am-draht/chatbottery-gpt-service/actions/workflows/analyse.yml/dispatches \
          -d '{"ref":"main","inputs":{"path":"${{ github.event.client_payload.path }}"}}'
